### PR TITLE
Added Password with Reveal Eye option

### PR DESCRIPTION
**Pull request by codepend**
Hi,

I've added a Reveal Password option to the RadzenPassword class. 

A couple things to note: 
I could not figure out the CSS structure so I re-used some classes from rz-calendar. I would be happy to fix/update this if I knew how.
I tried to follow Radzen's naming conventions.
I added a test as well as updated the components demo page.

Also, if you don't like this or the way it was done, I will not take it personally. Just trying to contribute.
Thanks for any consideration!

### CODE REVIEW

**Comment by enchev** [comment]
Hi @codepend,

Thanks for the pull request! 
There is a problem when width is defined
image

image

**Comment by codepend** [comment]
@enchev  I see. I will try and figure out.

**Comment by codepend** [comment]
I have implemented some changes which I believe resolve previously mentioned issues as well as added ability to allow password reveal while the component is Disabled. Happy to work on any issues you see with it.

**Comment by enchev** [comment]
please rebase your branch against the master in order to check your changes

**Comment by codepend** [comment]
I rebased this, believe it is up to date now using the new "config" components for demo pages

**Comment by akorchev** [comment]
The latest implementation is problematic as well. The Style is rendered twice which is wrong. Also there is another wrapper which seems unnecessary. I am closing this PR as this feature needs to be addressed by a more robust rendering implementation.

**Comment by codepend** [comment]
Thanks again for the consideration. I will try and work on something more appropriate.

**Comment by akorchev** [comment]
The biggest problem is the rendering. Adding a wrapper element is a breaking change and should be fully tested that it doesn't break too many cases. This is why we prefer to implement it ourselves. Thank you for your efforts though! We appreciate the good will.

If you need this for your application I would implement it in a custom component which renders RadzenPassword or RadzenTextBox depending on a property value which is toggled by the icon.

**Pull request closed without merging**
