### PR TITLE
Loop parameters once during SetParametersAsync

### PR DESCRIPTION
**Pull request by blake-fm**
Down from 6.

### CODE REVIEW

**Comment by blake-fm** [comment]
If you're interested, I can drop this over, also.  But it probably needs a bit more attention / clean up / add an allow param,so it's not a breaking change.
https://github.com/radzenhq/radzen-blazor/commit/e28565b712ae7ae54d9d0d8a3d834a026af92941

**Comment by enchev** [comment]
Hi @blake-fm,

Thanks for your pull request however I'm not sure what's the purpose of this change. Will it solve something?

**Comment by blake-fm** [comment]
By itself this is just optimisation.  `RadzenDataGrid` is currently looping through the list of parameters on every `SetParametersAsync` 6 times.  `SetParametersAsync` is called a lot more frequently than its name suggests.

The commit I mentioned in follow-up comment solves: `RadzenDataGrid` does not clean its list of selected items, when `SelectionMode` is changed from multiple to single.

When I added that ^ to my own code, I figured you could also benefit.  If you're not interested though, no worries!  Close away.

**Comment by enchev** [comment]
The most significant difference in my opinion is using EqualityComparer instead parameters.DidParameterChange() and I'm not sure if this is correctly.

**Comment by blake-fm** [comment]
That's an extension method in your `common.cs`.  It loops the parameter set and runs the same line.

**Comment by enchev** [comment]
Well, yes, I need more coffee!

**Pull request merged**
