### PR TITLE
Implemented speech to text for RadzenTextArea radzenhq#699

### PR DESCRIPTION
**Pull request by groogiam**
Implementation for https://github.com/radzenhq/radzen-blazor/issues/699

### CODE REVIEW

**Comment by akorchev** [comment]
Hi Greg,

We think the button should be a separate stand-alone component which can be used with other input components and not just RadzenTextArea. 

A drawback of your implementation is that the button is always rendered after the text area and there is no way to control its appearance and position via the RadzenTextArea API. Making it a separate component would solve this too.

**Comment by groogiam** [comment]
I'm running into some issues when implementing this. I am trying to pass the reference from the text input to the component that should be updated.

```
<RadzenTextArea @ref="textToSpeechInput" Change=@(args => OnChange(args, "TextArea")) Class="w-100" />
<RadzenSpeechToText AttachedInput="textToSpeechInput" ></RadzenSpeechToText>
```

The problem here is that the @ref does not get populated until after the initial render so the button does not show up until an explicit re-render. Any idea on how to make this work or would another approach be to implement value binding and just have users wire up the data binding to the same property as the textbox? Looking forward to your input. Thanks.

**Comment by groogiam** [comment]
After giving this some thought it seems like the best approach would be to just have the component raise an event call back with the speech results while it is active. This is the simplest implementation and gives the caller the most flexibility as to what they want to do with the results. It also allows for use cases where the user does not want to write the result to a component. Let me know if you agree. Thanks.

**Comment by groogiam** [comment]
Closing in favor of https://github.com/radzenhq/radzen-blazor/pull/703

**Pull request closed without merging**
