### PR TITLE
#1320 Cascade RadzenDataGrid class to all descendants

### PR DESCRIPTION
**Pull request by djatkinsrealis**
Move the RadzenDataGrid cascading value to surround the entire component, allowing it to be picked up in customer header/footer etc. Splitting the existing CascadingValue to lines 8 (before all HTML) and approx line 435 just before the @code

### CODE REVIEW

**Comment by enchev** [comment]
Before: 2.6 MB binary message
image
image

After change 2.9 MB binary message
image
image

In my opinion this in unacceptable.

**Comment by djatkinsrealis** [comment]
@enchev Can we get more info on how you test the above, so we can do equivalent checks before submissions?

**Comment by enchev** [comment]
You can easily test the size of the Blazor binary message using our Dynamic data binding demo.
Just set PageSize=100 and press Run in the demo code editor - messages can be observed in your browser network tab for the Blazor WebSocket connection.

**Comment by enchev** [comment]
Check this issue also:
https://github.com/radzenhq/radzen-blazor/issues/1228

**Comment by djatkinsrealis** [comment]
@enchev Hi again, I was very puzzled that a cascade could affect message size so much, so I have been testing that 2-line PR change _only_, in release builds, against the same master branch it was branched from. The only difference being the split of the cascading value to wrap the entire component (and the PageSize=100 in both of course). In both cases I am seeing 2.7Mb message size consistently. Screen shots below (master then branch):
image
image

**Comment by enchev** [comment]
I was testing in Debug, good catch! Now after I've tested the same in release I received 2.6 MB for both branches - I proceed and merge your change.

**Pull request merged**
