### PR TITLE
Added an Image property for RadzenLink

### PR DESCRIPTION
**Pull request by gauss-lvs-dev**
I have added an image property to the RadzenLink component analogous to the RadzenButton component.

### CODE REVIEW

**Comment by enchev** [comment]
Hi @gauss-lvs-dev,

The change looks OK to me, do you plan to add anything else?

**Comment by gauss-lvs-dev** [comment]
No I am not. I just created a draft in case someone of you had any other suggestions :).

**Comment by akorchev** [comment]
Hi @gauss-lvs-dev,

Please undo your last commit that changes Version to VersionPrefix.

**Comment by gauss-lvs-dev** [comment]
The changes in regards to Version and VersionPrefix were not supposed to be in this pull request. Sorry.

**Comment by gauss-lvs-dev** [comment]
I reverted those changes.

**Pull request merged**
