### PR TITLE
Can change added

### PR DESCRIPTION
**Pull request by marekm294**
Image situation: ask user if he really wants to change step with dialog. Or maybe ask user, if he wants to change current step without saving changes made in this step.
This PR allows both

### CODE REVIEW

**Comment by akorchev** [comment]
Hi @marekm294,

What's the purpose of this PR? It has no description provided about its intent.

**Comment by marekm294** [comment]
@akorchev  - Done :)

**Comment by marekm294** [comment]
demo added

**Comment by akorchev** [comment]
Thank you for the demo. I understand the intent now. Unfortunately this API is quite strange considering the existing events. There also are two events `CanChange` and `CanChangeAsync`. Could you try implementing it with a single `EventCallback` similar to [this](https://github.com/radzenhq/radzen-blazor/blob/master/Radzen.Blazor/RadzenScheduler.razor.cs#L187)? It would then support both async and sync handlers.

```
<RadzenTabs CanChange=@CanChange>
</RadzenTabs>

@code {
    async Task CanChange(RadzenTabsCanChangeEventArgs args)
    {
        if (condition)
        {
            args.PreventDefault();
        }
    }
} 
```

**Comment by marekm294** [comment]
I hope I understood you

**Comment by akorchev** [comment]
That's exactly what I meant! Just please rename`PreventStepChange()` to `PreventDefault()` (for consistency with other components) and `IsStepChangePrevented` to `IsDefaultPrevented`.

**Pull request merged**
