### PR TITLE
Render chart tooltips in the same way as standard tooltips

### LINKED ISSUE #560: LineChart Tooltip near to the browser end doesn't work
If I have a LineChart and a tooltips is shown in the near of the left end of the display/browser, it will only show a part of the tooltip, the rest is cut by the end of the screen

```
<RadzenChart @ref="chart0">
        @foreach(var item in delevererEKDatas!)
        {
            string tile = item.LineName;
                string color = getRandomColor(item.MainDeliverer);
                <RadzenLineSeries Stroke="@color" Smooth="@smooth" Data="@item.EKData" CategoryProperty="Date" Title=@tile LineType="LineType.Solid" ValueProperty="Price">
                    <ChildContent>
                        <RadzenMarkers MarkerType="MarkerType.Auto" Stroke="@color" />
                    </ChildContent>
                    <TooltipTemplate Context="data">
                    <div>
                        @data.DelInfo<br/>
                        <strong>@data.Date.ToString("dddd, dd MMMM yyyy")</strong><br/>
                        <strong>EK-Preis: @data.Price.ToString("N2")</strong><br/>
                        ab Menge @data.MinQuantity.ToString("N0")<br/>
                            @if (@data.AvailableQuantity is not null) 
                            { 
                                <span>verfügbare Menge: @data.AvailableQuantity</span>
                            }
                    </div>
                    </TooltipTemplate>
                </RadzenLineSeries>
            }
    
        <RadzenCategoryAxis  Padding="20" Min="@searchArticleDateDeliverer.StartDate" Max="@searchArticleDateDeliverer.EndDate" Step="31" FormatString="{0:dd.MM.yy}" />
        <RadzenValueAxis Formatter="@FormatAsEURO">
            <RadzenGridLines Visible="true" />
        </RadzenValueAxis>
        @if(delevererEKDatas.Count == 1)
        {
                <RadzenLegend Position="LegendPosition.Bottom" Visible="false" />
        }
        else if(delevererEKDatas.Count > 4)
        {
            <RadzenLegend Position="LegendPosition.Right" Visible="true" />
        }
        else
        {
            <RadzenLegend Position="LegendPosition.Bottom" Visible="true" />
        }
    </RadzenChart> 
```

### PR DESCRIPTION
**Pull request by maxbruecken**
This PR changes rendering of chart tooltip so, that chart tooltips are shown above all another controls, like the standard tooltips. This PR should fix #560.
Unfortunaltely there are some breaking changes:
- Implementations of IChartSeries and IChartSeriesOverlay in external projects using Radzen must be updated
- RadzenChartTooltip should be included in e.g. MainLayout.razor and ChartTooltipService should bei injected. No changes are necessary if RadzenComponents.razor and .AddRadzenComponents() are already used

### CODE REVIEW

**Comment by akorchev** [comment]
Hi @maxbruecken,

Thank you for the PR!

A few questions:

1. Is a tooltip service really needed?
2. If it is needed can't the existing one be used instead of creating a separate one (which seems almost identical). If needed I would suggest extending the existing one with a new method (OpenChartTooltip etc - which could be internal).

**Comment by maxbruecken** [comment]
Hi @akorchev,

thank you for reviewing my PR.
1. yes, the tooltip service ist needed. The chart tooltip component is now outside of the chart, so there should be a service, that can be injected in both components
2. sure, I can move the new method from ChartTooltipService to existing TooltipService and make it internal.
3. I can implement the flipping of the tooltip on the top end of the page, I guess, the method 'openPopup' in Radzen.Blazor.js must be slightly changed, the standard tooltip seems to have the same issue (flipping on the bottom end seems to work):

image

**Comment by maxbruecken** [comment]
Hi @akorchev,

I have moved the OpenChartTooltip method to the TooltipService and removed the ChartTooltipService. The chart tooltip will be shown under the series point now, if there isn't enough space above the series point.

**Comment by akorchev** [comment]
I've made a few things internal. Thanks!

**Pull request merged**
