### PR TITLE
Added AdditionalContent Parameter to Scheduler

### PR DESCRIPTION
**Pull request by bikotoru**
### 

This PR introduces a new parameter, `AdditionalContent`, to the scheduler component. It allows developers to add custom content next to the year, month, and day buttons, providing more flexibility for adding additional controls or information to the scheduler's header area.

#### Changes:
- Added `AdditionalContent` parameter of type `RenderFragment`.
- Updated documentation comments to describe the parameter's functionality.

This feature improves the customizability of the scheduler and addresses the need for more adaptable UI elements.

Please review the implementation and let me know if there are any changes needed.

### CODE REVIEW

**Comment by akorchev** [comment]
Hi @bikotoru,

Thank you for the PR. Can we think of a better name than AdditionalContent? It isn't clear where this additional content will go.

**Comment by bikotoru** [comment]
PersonalizedView?
CustomView? 
I'm kind of bad with names haha

**Comment by akorchev** [comment]
What is the purpose of this to begin with? What do you want to add there?

**Comment by bikotoru** [comment]
@akorchev  
For example a Refresh Button

**Comment by akorchev** [comment]
What bothers me is that it renders together with the default navigation (and the name). Somebody would ask for it to render **before** and not **after**. I can propose a different implementation - NavigationTemplate which replaces the whole navigation section - easier to name and provides full control. The existing navigation can be emulated with existing components too. What do you think?

**Comment by bikotoru** [comment]
perfect I have applied the change

**Pull request merged**
