### PR TITLE
New splitter component

### PR DESCRIPTION
**Pull request by GioeEng**
Implementation of the new Splitter component. Theme settings are missing. Variables already implemented in _splitter.scss

### CODE REVIEW

**Comment by akorchev** [comment]
Hi @GioeEng,

Thank you for the pull request and the enormous amount of work. We appreciate the effort!

We will have to test the behavior of the component before we merge it though. 

Also here are a few comments that I have after a quick glance over the implementation (they are mostly about code style and naming conventions).

1. The events of Radzen components currently do not begin with On - we prefer Resize vs. OnResize.
2. All CSS classes that we use have a common prefix ".rz-" e.g.  class="rz-collapse" vs. class="collapse"
3. We use camel case notation for C# and JS variable names e.g. `pane` vs `i_pane` and `paneLength` vs `pane_length`.

Could you please update the code to adhere to those conventions?

**Comment by GioeEng** [comment]
Hi @akorchev,
Within the time available, reported problems were fixed and some bug fixes were performed

**Comment by akorchev** [comment]
Thank you @GioeEng! I just played around with this pull request and things look very promising! Great stuff.

We just need to style it a bit and implement design-time support in Radzen. By the way we want to give you a free Radzen Professional subscription (if you want one of course). Just shoot an email to info@radzen.com.

**Comment by GioeEng** [comment]
Thanks @akorchev , 
actually I didn't focus on styles as I don't have all the tools needed for theme setup assistant. I'm thinking of using the Razden library to migrate my AspNet.Core (MVC) projects and its library of javascript controls. There are still several controls and features I can implement (from the old library) but I'm waiting for Microsoft to improve Blazor integration with VS (2022? https://devblogs.microsoft.com/dotnet/introducing-net-hot-reload/) because working without the edit & continue and without Hot Reload properly functional is really time consuming.
It's still a pleasure to collaborate, you are doing a good job.

**Comment by akorchev** [comment]
We have a design for the splitter in mind and will implement it some time next week (hopefully).

**Pull request merged**
