### PR TITLE
Added "Custom" to FilterOperator for manually building a custom filter

### PR DESCRIPTION
**Pull request by k-Sacr**
Added a Custom filter to FilterOperator for manually building custom filter.
Column with FilterOperator.Custom will not be taken for constructing filterString in args.Filter, but will be taken in args.filters. This will allow the user to manually build a custom and more complex filter.

A simple example, combining first name and last name and phone number in one column and a one filter for them.
Or displaying data from related tables and more complex filtering by Include table

https://github.com/radzenhq/radzen-blazor/assets/18440948/98d9a1d9-116f-4413-9046-4af86a1e423d

devenv_2023-09-27_01-34-52

devenv_2023-09-27_01-35-59

Demo code:
```
@using System.Linq.Dynamic.Core
@using Microsoft.EntityFrameworkCore
@using RadzenBlazorDemos.Data
@using RadzenBlazorDemos.Models.Northwind

@inherits DbContextPage

<RadzenButton Text="Reset" Click="@Reset" Style="margin-bottom: 20px;" />
<RadzenDataGrid style="height: 335px" @ref="grid" IsLoading=@isLoading Count="@count" Data="@employees"
                LoadData="@LoadData" AllowSorting="true" AllowFiltering="true" AllowPaging="true" PageSize="10" 
                PagerHorizontalAlign="HorizontalAlign.Center" TItem="Employee" ColumnWidth="200px"
                FilterMode="FilterMode.Simple" >
    <Columns>
        <RadzenDataGridColumn TItem="Employee" Property="EmployeeID" Filterable="false" Title="ID" Frozen="true" Width="80px" TextAlign="TextAlign.Center" />
        <RadzenDataGridColumn TItem="Employee" Title="Photo" Frozen="true" Sortable="false" Filterable="false" Width="80px" TextAlign="TextAlign.Center" >
            <Template Context="data">
                <RadzenImage Path="@data.Photo" class="rz-gravatar" />
            </Template>
        </RadzenDataGridColumn>  

        <RadzenDataGridColumn TItem="Employee" Property="FirstName" Title="Employee" FilterOperator="FilterOperator.Custom">
	        <Template Context="data">
		        @data.FirstName @data.LastName   
		        <br>
                @data.HomePhone
	        </Template>
        </RadzenDataGridColumn>

        <RadzenDataGridColumn Width="250px" TItem="Employee" Property="Orders" Title="Orders" FilterOperator="FilterOperator.Custom">
	        <Template Context="data">
		        <span style="white-space: pre-wrap;">
			        @string.Join(", ", data?.Orders?.Select(o => o.OrderID).ToList() ?? new List<int>())
		        </span>
	        </Template>
        </RadzenDataGridColumn>

        <RadzenDataGridColumn TItem="Employee" Property="Title" Title="Job Title" 
            Type="typeof(IEnumerable<string>)" FilterValue="@selectedTitles" FilterOperator="FilterOperator.Contains" Width="200px">
            <FilterTemplate>
                <RadzenDropDown @bind-Value=@selectedTitles Style="width:100%"
                    Change=@OnSelectedTitlesChange Data="@(titles)" AllowClear="true" Multiple="true" />
            </FilterTemplate>
        </RadzenDataGridColumn>
        <RadzenDataGridColumn TItem="Employee" Property="TitleOfCourtesy" Title="Title" Width="120px" />
        <RadzenDataGridColumn TItem="Employee" Property="BirthDate" Title="Birth Date" FormatString="{0:d}" Width="160px" />
        <RadzenDataGridColumn TItem="Employee" Property="HireDate" Title="Hire Date" FormatString="{0:d}" Width="160px" />
        <RadzenDataGridColumn TItem="Employee" Property="Address" Title="Address" Width="200px" />
        <RadzenDataGridColumn TItem="Employee" Property="City" Title="City" Width="160px" />
        <RadzenDataGridColumn TItem="Employee" Property="Region" Title="Region" Width="160px" />
        <RadzenDataGridColumn TItem="Employee" Property="PostalCode" Title="Postal Code" Width="160px" />
        <RadzenDataGridColumn TItem="Employee" Property="Country" Title="Country" Width="160px" />
        <RadzenDataGridColumn TItem="Employee" Property="HomePhone" Title="Home Phone" Width="160px" />
        <RadzenDataGridColumn TItem="Employee" Property="Extension" Title="Extension" Width="160px" />
        <RadzenDataGridColumn TItem="Employee" Property="Notes" Title="Notes" Width="300px" />
    </Columns>
</RadzenDataGrid>

@code {
    RadzenDataGrid<Employee> grid;
    int count;
    IEnumerable<Employee> employees;
    bool isLoading = false;

    List<string> titles = new List<string> {"Sales Representative", "Vice President, Sales", "Sales Manager", "Inside Sales Coordinator" };
    IEnumerable<string> selectedTitles;

    async Task OnSelectedTitlesChange(object value)
    {
        if (selectedTitles != null && !selectedTitles.Any())
        {
            selectedTitles = null;  
        }
        
        await grid.FirstPage();
    }

    async Task Reset()
    {
        grid.Reset(true); 
        await grid.FirstPage(true);
    }

    async Task LoadData(LoadDataArgs args)
    {
        isLoading = true;

        await Task.Yield();

        // This demo is using https://dynamic-linq.net
        var query = dbContext.Employees
	        .Include(e => e.Orders)
	        .AsQueryable();

        if (!string.IsNullOrEmpty(args.Filter))
        {
            // Filter via the Where method
            query = query.Where(args.Filter);
        }

	    var nameFilter = args.Filters
		    .FirstOrDefault(d => d.FilterOperator == FilterOperator.Custom && d.Property == nameof(Employee.FirstName))
		    ?.FilterValue.ToString();
        if (!string.IsNullOrWhiteSpace(nameFilter))
        {
	        query = query.Where(e => e.FirstName.Contains(nameFilter, StringComparison.OrdinalIgnoreCase)
                                     || e.LastName.Contains(nameFilter, StringComparison.OrdinalIgnoreCase) 
                                     || e.HomePhone.Contains(nameFilter, StringComparison.OrdinalIgnoreCase));
        }
	    
	    var orderFilter = args.Filters?
		    .FirstOrDefault(d => d.FilterOperator == FilterOperator.Custom && d.Property == nameof(Employee.Orders))
		    ?.FilterValue.ToString();
        if (!string.IsNullOrWhiteSpace(orderFilter))
        {
	        int orderId = int.Parse(orderFilter);
            query = query.Where(e => e.Orders.Any(o => o.OrderID == orderId));
        }

        if (!string.IsNullOrEmpty(args.OrderBy))
        {
            // Sort via the OrderBy method
            query = query.OrderBy(args.OrderBy);
        }

        // Important!!! Make sure the Count property of RadzenDataGrid is set.
        count = query.Count();

        // Perform paging via Skip and Take.
        employees = query.Skip(args.Skip.Value).Take(args.Top.Value).ToList();

        isLoading = false;
    }
}
```

### CODE REVIEW

**Comment by enchev** [comment]
Thanks for the pull request @k-Sacr however I have some remarks. Since you are using LoadData you have full control on how the filtering will be applied and this code can be reworked to work even now without any changes:
```
 var nameFilter = args.Filters
		    .FirstOrDefault(d => d.Property == nameof(Employee.FirstName))
		    ?.FilterValue.ToString();
```
Not sure also about the `FilterOperator.Custom` in context of IQueryable filtering. In my opinion we have now pretty powerful instruments for custom filtering using FilterTemplate and FilterValueTemplate/SecondFIlterValueTemplate that can work in both IQueryable and LoadData binding - no need to mark a column additionally that will use custom filter.

**Comment by k-Sacr** [comment]
> Thanks for the pull request @k-Sacr however I have some remarks. Since you are using LoadData you have full control on how the filtering will be applied and this code can be reworked to work even now without any changes:

Yes, if not used `query = query.Where(args.Filter);` otherwise, without FilterOperator.Custom, the filter will end up in args.Filter. 
With FilterOperator.Custom you can easily use a combination of args.Filter and args.Filters.


> Not sure also about the `FilterOperator.Custom` in context of IQueryable filtering. In my opinion we have now pretty powerful instruments for custom filtering using FilterTemplate and FilterValueTemplate/SecondFIlterValueTemplate that can work in both IQueryable and LoadData binding - no need to mark a column additionally that will use custom filter.

Yes, but it's a FilterTemplate for complex UI filters. 
And the Value from the FilterTemplate is still set to RadzenDataGridColumn FilterValue, then build to args.Filter, which is what should be avoided, but must be received in args.Filters

Perhaps there is a way to get the filter in args.Filters, but avoid it in args.Filter?

But by adding just 1 value to the enum, it will greatly simplify the code, you won't have to use an extra "FilterTemplate" (no need to add props for @bind-Value) for all custom filters, and most importantly, it won't affect those does not use FilterOperator.Custom.

**Comment by k-Sacr** [comment]
Сombination of args.Filter and args.Filters (with FilterOperator.Custom):

https://github.com/radzenhq/radzen-blazor/assets/18440948/01a5629b-9399-4727-95fb-c50abe73cd61

devenv_2023-09-27_14-19-35

**Comment by k-Sacr** [comment]
> Yes, `ToFilterString()` accepts `IEnumerable<RadzenDataGridColumn<T>>` and you can exclude desired column:
Thanks, this actually works on the demo version. 

Like this?
```
 var columns = grid.ColumnsCollection
	    .Where(d => d.Property != nameof(Employee.FirstName) && d.Property != nameof(Employee.Orders))
	    .ToList();

 var filterString = columns.ToFilterString();
```
The bad thing is that need access to `grid` (`@ref="grid"`) in `LoadData(LoadDataArgs args)`. We have them in different layers, LoadData is located in the service for working with the database.

> My concern is that such filter operator cannot be used in IQueryable binding

It may be possible to further expand this idea and allow the user to using his own `FilterStringTemplate` (example) using DynamicLinq with FilterOperator.Custom


https://github.com/radzenhq/radzen-blazor/assets/18440948/ecdbb473-10f9-49cd-a725-8e54c806e5b0


devenv_2023-09-27_16-19-21

**Comment by k-Sacr** [comment]
Thank you!

**Pull request merged**
